name: Docker CI/CD with Versioning

on:
  push:
    tags:
      - 'v*'  # Triggers only when a version tag like v1.2 is pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/howler-client:${{ env.VERSION }} ./client
          docker tag ${{ secrets.DOCKER_USERNAME }}/howler-client:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/howler-client:latest


      #backend not ready yet
      # - name: Build backend
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/howler-server:${{ env.VERSION }} ./server
      #     docker tag ${{ secrets.DOCKER_USERNAME }}/howler-server:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/howler-server:latest

      - name: Push frontend images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/howler-client:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/howler-client:latest

      # - name: Push backend images
      #   run: |
      #     docker push ${{ secrets.DOCKER_USERNAME }}/howler-server:${{ env.VERSION }}
      #     docker push ${{ secrets.DOCKER_USERNAME }}/howler-server:latest
